# This is a YAML version of inventory file.
# Ansible uses this to know which machines to target based on the pattern used.

LINUX: 
  children:
    LINUX_GROUP_SAMPLE:
      hosts:
        Ansible-Sample-Machine-Lin:
          ansible_host: 192.168.1.1


MAC:
  children:
    MAC_GROUP_SAMPLE: 
      hosts:
        Ansible-Sample-Machine-Mac:
          ansible_host: 192.168.1.1


WINDOWS:
  vars:
    ansible_password: '{{ windows_password }}'
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5985
  children:
    WINDOWS_GROUP_SAMPLE:
      Ansible-Sample-Machine-Win:
          ansible_host: 192.168.1.1
